### ISSUE TITLE
delete remove two numbers instead of one

### ISSUE THREAD

**Issue by sgehrman** [devfun052017/pin_entry_field#1]
i type 1111
hit delete and now it's 11

**Comment by devfun052017** [comment]
Hello Steve,

Please switch to channel stable. This is Flutter issue

Vào Th 3, 1 thg 12, 2020 vào lúc 10:46 Steve Gehrman <
notifications@github.com> đã viết:

**Comment by sgehrman** [comment]
yeah, I just found that on github issues.  master branch works. I thought I read it was only on master?  anyway, it's working now.
